### ISSUE TITLE
NullPointerException at play.utils.UriEncoding$.encodePathSegment

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/NemakiWare#161]
Immediately after installing and starting, catalina.out shows:

```
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
07-Oct-2015 18:36:54.614 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.26
07-Oct-2015 18:36:54.619 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 18 2015 11:38:37 UTC
07-Oct-2015 18:36:54.619 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.26.0
07-Oct-2015 18:36:54.620 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
07-Oct-2015 18:36:54.621 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.19.0-30-generic
07-Oct-2015 18:36:54.621 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
07-Oct-2015 18:36:54.622 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-7-oracle/jre
07-Oct-2015 18:36:54.622 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.7.0_80-b15
07-Oct-2015 18:36:54.623 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
07-Oct-2015 18:36:54.623 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /home/nico/p/nemakiware/apache-tomcat-8.0.26
07-Oct-2015 18:36:54.624 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /home/nico/p/nemakiware/apache-tomcat-8.0.26
07-Oct-2015 18:36:54.625 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -javaagent:/usr/share/java/jayatanaag.jar
07-Oct-2015 18:36:54.626 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/home/nico/p/nemakiware/apache-tomcat-8.0.26/conf/logging.properties
07-Oct-2015 18:36:54.626 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
07-Oct-2015 18:36:54.627 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms128m
07-Oct-2015 18:36:54.627 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024m
07-Oct-2015 18:36:54.628 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxPermSize=256m
07-Oct-2015 18:36:54.628 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dfile.encoding=UTF-8
07-Oct-2015 18:36:54.629 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/home/nico/p/nemakiware/apache-tomcat-8.0.26/endorsed
07-Oct-2015 18:36:54.630 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/home/nico/p/nemakiware/apache-tomcat-8.0.26
07-Oct-2015 18:36:54.630 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/home/nico/p/nemakiware/apache-tomcat-8.0.26
07-Oct-2015 18:36:54.631 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/home/nico/p/nemakiware/apache-tomcat-8.0.26/temp
07-Oct-2015 18:36:54.631 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
07-Oct-2015 18:36:55.710 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
07-Oct-2015 18:36:55.815 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
07-Oct-2015 18:36:55.828 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
07-Oct-2015 18:36:55.838 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
07-Oct-2015 18:36:55.839 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 3658 ms
07-Oct-2015 18:36:56.037 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
07-Oct-2015 18:36:56.038 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.26
07-Oct-2015 18:36:56.144 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor /home/nico/p/nemakiware/apache-tomcat-8.0.26/conf/Catalina/localhost/solr.xml
07-Oct-2015 18:36:56.268 WARNING [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor A docBase /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/solr inside the host appBase has been specified, and will be ignored
07-Oct-2015 18:37:21.971 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:WARN No appenders could be found for logger (org.apache.solr.client.solrj.impl.HttpClientUtil).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
07-Oct-2015 18:37:36.978 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor /home/nico/p/nemakiware/apache-tomcat-8.0.26/conf/Catalina/localhost/solr.xml has finished in 40,829 ms
07-Oct-2015 18:37:36.986 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/core.war
07-Oct-2015 18:37:48.418 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:WARN No appenders could be found for logger (org.springframework.web.context.ContextLoader).
log4j:WARN Please initialize the log4j system properly.
07-Oct-2015 18:38:05.338 INFO [localhost-startStop-1] com.sun.xml.ws.transport.http.servlet.WSServletContextListener.contextInitialized WSSERVLET12: JAX-WS context listener initializing
07-Oct-2015 18:38:28.672 INFO [localhost-startStop-1] com.sun.xml.ws.transport.http.servlet.WSServletDelegate.<init> WSSERVLET14: JAX-WS servlet initializing
07-Oct-2015 18:38:28.753 INFO [localhost-startStop-1] com.sun.jersey.api.core.PackagesResourceConfig.init Scanning for root resource and provider classes in the packages:
  jp.aegif.nemaki.api.resources
07-Oct-2015 18:38:29.153 INFO [localhost-startStop-1] com.sun.jersey.spi.spring.container.servlet.SpringServlet.getContext Using default applicationContext
07-Oct-2015 18:38:29.162 INFO [localhost-startStop-1] com.sun.jersey.spi.spring.container.SpringComponentProviderFactory.registerSpringBeans Registering Spring bean, archiveResource, of type jp.aegif.nemaki.rest.ArchiveResource as a root resource class
07-Oct-2015 18:38:29.163 INFO [localhost-startStop-1] com.sun.jersey.spi.spring.container.SpringComponentProviderFactory.registerSpringBeans Registering Spring bean, userResource, of type jp.aegif.nemaki.rest.UserResource as a root resource class
07-Oct-2015 18:38:29.163 INFO [localhost-startStop-1] com.sun.jersey.spi.spring.container.SpringComponentProviderFactory.registerSpringBeans Registering Spring bean, groupResource, of type jp.aegif.nemaki.rest.GroupResource as a root resource class
07-Oct-2015 18:38:29.164 INFO [localhost-startStop-1] com.sun.jersey.spi.spring.container.SpringComponentProviderFactory.registerSpringBeans Registering Spring bean, typeResource, of type jp.aegif.nemaki.rest.TypeResource as a root resource class
07-Oct-2015 18:38:29.164 INFO [localhost-startStop-1] com.sun.jersey.spi.spring.container.SpringComponentProviderFactory.registerSpringBeans Registering Spring bean, solrResource, of type jp.aegif.nemaki.rest.SolrResource as a root resource class
07-Oct-2015 18:38:29.165 INFO [localhost-startStop-1] com.sun.jersey.spi.spring.container.SpringComponentProviderFactory.registerSpringBeans Registering Spring bean, solrAllResource, of type jp.aegif.nemaki.rest.SolrAllResource as a root resource class
07-Oct-2015 18:38:29.165 INFO [localhost-startStop-1] com.sun.jersey.spi.spring.container.SpringComponentProviderFactory.registerSpringBeans Registering Spring bean, authtokenResource, of type jp.aegif.nemaki.rest.AuthTokenResource as a root resource class
07-Oct-2015 18:38:29.179 INFO [localhost-startStop-1] com.sun.jersey.server.impl.application.WebApplicationImpl._initiate Initiating Jersey application, version 'Jersey: 1.17.1 02/28/2013 12:47 PM'
07-Oct-2015 18:38:31.361 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/core.war has finished in 54,376 ms
07-Oct-2015 18:38:31.363 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/ui.war
07-Oct-2015 18:38:46.449 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
[[37minfo[0m] play - Force Play 'application.context' to '/ui/'
[[37minfo[0m] application - Application has started
[[37minfo[0m] play - Application started (Prod)
07-Oct-2015 18:38:51.762 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/ui.war has finished in 20,399 ms
07-Oct-2015 18:38:51.766 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/ROOT
07-Oct-2015 18:38:51.878 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
07-Oct-2015 18:38:51.885 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/ROOT has finished in 120 ms
07-Oct-2015 18:38:51.886 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/examples
07-Oct-2015 18:38:52.845 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
07-Oct-2015 18:38:53.032 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/examples has finished in 1,146 ms
07-Oct-2015 18:38:53.033 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/docs
07-Oct-2015 18:38:53.148 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
07-Oct-2015 18:38:53.156 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/docs has finished in 123 ms
07-Oct-2015 18:38:53.161 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/host-manager
07-Oct-2015 18:38:53.283 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
07-Oct-2015 18:38:53.292 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/host-manager has finished in 131 ms
07-Oct-2015 18:38:53.293 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/manager
07-Oct-2015 18:38:53.421 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
07-Oct-2015 18:38:53.429 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/nico/p/nemakiware/apache-tomcat-8.0.26/webapps/manager has finished in 136 ms
07-Oct-2015 18:38:53.528 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
07-Oct-2015 18:38:53.556 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
07-Oct-2015 18:38:53.558 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 117718 ms
[[31merror[0m] play - Cannot invoke the action, eventually got an error: java.lang.NullPointerException
[[31merror[0m] application - 

! @6nl2cddn6 - Internal server error, for (GET) [/ui/repo/bedroom/] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.3.jar:2.3.3]
	at play.core.server.servlet.DefaultWarApplication.handleError(Play2Server.scala:118) [com.github.play2war.play2-war-core-common_2.11-1.3-beta2.jar:1.3-beta2]
	at play.core.server.servlet.Play2GenericServletRequestHandler$$anonfun$1$$anonfun$applyOrElse$7.apply(RequestHandler.scala:376) [com.github.play2war.play2-war-core-common_2.11-1.3-beta2.jar:1.3-beta2]
	at play.core.server.servlet.Play2GenericServletRequestHandler$$anonfun$1$$anonfun$applyOrElse$7.apply(RequestHandler.scala:376) [com.github.play2war.play2-war-core-common_2.11-1.3-beta2.jar:1.3-beta2]
	at scala.Option.fold(Option.scala:158) [org.scala-lang.scala-library-2.11.6.jar:na]
Caused by: java.lang.NullPointerException: null
	at play.utils.UriEncoding$.encodePathSegment(UriEncoding.scala:46) ~[com.typesafe.play.play_2.11-2.3.3.jar:2.3.3]
	at play.core.Router$.dynamicString(Router.scala:153) ~[com.typesafe.play.play_2.11-2.3.3.jar:2.3.3]
	at controllers.ReverseApplication.login(routes_reverseRouting.scala:394) ~[ui_2.11-2.1.jar:2.1]
	at controllers.Secured.onUnauthorized(Secured.java:20) ~[ui_2.11-2.1.jar:2.1]
	at play.mvc.Security$AuthenticatedAction.call(Security.java:39) ~[com.typesafe.play.play_2.11-2.3.3.jar:2.3.3]
07-Oct-2015 18:38:58.830 SEVERE [http-nio-8080-exec-5] com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle Couldn't create SOAP message due to exception: org.jvnet.mimepull.MIMEParsingException: Reached EOF, but there is no closing MIME boundary.
 com.sun.xml.ws.protocol.soap.MessageCreationException: Couldn't create SOAP message due to exception: org.jvnet.mimepull.MIMEParsingException: Reached EOF, but there is no closing MIME boundary.
	at com.sun.xml.ws.encoding.SOAPBindingCodec.decode(SOAPBindingCodec.java:365)
	at com.sun.xml.ws.transport.http.HttpAdapter.decodePacket(HttpAdapter.java:277)
	at com.sun.xml.ws.transport.http.HttpAdapter.access$500(HttpAdapter.java:93)
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:457)
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:244)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:135)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:129)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:160)
	at com.sun.xml.ws.transport.http.servlet.WSServlet.doPost(WSServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.apache.chemistry.opencmis.server.impl.webservices.CmisWebServicesServlet.service(CmisWebServicesServlet.java:154)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jvnet.mimepull.MIMEParsingException: Reached EOF, but there is no closing MIME boundary.
	at org.jvnet.mimepull.MIMEParser.readBody(MIMEParser.java:225)
	at org.jvnet.mimepull.MIMEParser.access$600(MIMEParser.java:68)
	at org.jvnet.mimepull.MIMEParser$MIMEEventIterator.next(MIMEParser.java:165)
	at org.jvnet.mimepull.MIMEParser$MIMEEventIterator.next(MIMEParser.java:132)
	at org.jvnet.mimepull.MIMEMessage.makeProgress(MIMEMessage.java:198)
	at org.jvnet.mimepull.DataHead.read(DataHead.java:144)
	at org.jvnet.mimepull.MIMEPart.read(MIMEPart.java:94)
	at com.sun.xml.ws.encoding.MimeMultipartParser$PartAttachment.asInputStream(MimeMultipartParser.java:196)
	at com.sun.xml.ws.encoding.MtomCodec.decode(MtomCodec.java:244)
	at com.sun.xml.ws.encoding.SOAPBindingCodec.decode(SOAPBindingCodec.java:409)
	at com.sun.xml.ws.encoding.MimeCodec.decode(MimeCodec.java:181)
	at com.sun.xml.ws.encoding.SOAPBindingCodec.decode(SOAPBindingCodec.java:352)
	... 32 more

2015-10-07 18:39:02,409 WARN  [http-nio-8080-exec-8] : Unsupported StAX parser: com.ctc.wstx.stax.WstxOutputFactory (Exception: java.lang.IllegalArgumentException: Unrecognized property 'com.ctc.wstx.outputInvalidCharHandler')
java.lang.IllegalArgumentException: Unrecognized property 'com.ctc.wstx.outputInvalidCharHandler'
	at com.ctc.wstx.api.CommonConfig.setProperty(CommonConfig.java:110)
	at com.ctc.wstx.stax.WstxOutputFactory.setProperty(WstxOutputFactory.java:153)
	at org.apache.chemistry.opencmis.commons.impl.XMLUtils.<clinit>(XMLUtils.java:94)
	at org.apache.chemistry.opencmis.commons.impl.tube.server.WssTube.processResponse(WssTube.java:61)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:608)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:557)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:542)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:439)
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:243)
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:471)
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:244)
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:135)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:129)
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:160)
	at com.sun.xml.ws.transport.http.servlet.WSServlet.doPost(WSServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.apache.chemistry.opencmis.server.impl.webservices.CmisWebServicesServlet.service(CmisWebServicesServlet.java:154)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nicolas-raoul** [comment]
The CMIS repository is working fine though, accessed from CMIS Workbench.
