### ISSUE TITLE
FileNotFoundException core.war

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/NemakiWare#248]
Following instructions at https://github.com/aegif/NemakiWare/wiki/Development_-Build-installer
```
-> Fatal error :
   /home/nico/src/nemaki/setup/installer/install.xml:144: /home/nico/src/nemaki/core/target/core.war
com.izforge.izpack.compiler.CompilerException: /home/nico/src/nemaki/setup/installer/install.xml:144: /home/nico/src/nemaki/core/target/core.war
        at com.izforge.izpack.compiler.CompilerConfig.parseError(Unknown Source)
        at com.izforge.izpack.compiler.CompilerConfig.addPacksSingle(Unknown Source)
        at com.izforge.izpack.compiler.CompilerConfig.addPacks(Unknown Source)
        at com.izforge.izpack.compiler.CompilerConfig.executeCompiler(Unknown Source)
        at com.izforge.izpack.compiler.CompilerConfig.main(Unknown Source)
        at com.izforge.izpack.compiler.Compiler.main(Unknown Source)
Caused by: java.io.FileNotFoundException: /home/nico/src/nemaki/core/target/core.war
        at com.izforge.izpack.compiler.PackInfo.addFile(Unknown Source)
        at com.izforge.izpack.compiler.CompilerConfig.addRecursively(Unknown Source)
        ... 5 more
```

**Comment by nicolas-raoul** [comment]
Fixed wiki
