### ISSUE TITLE
nemakisolr_installer can't find "webapps" folder of existing Tomcat in custom location

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/NemakiWare#26]
```
  [...]
  inflating: /home/nico/p/nemakiware/apache-tomcat-7.0.41/webapps/manager/xform.xsl  
configure tomcat
nico@nico:~/src/NemakiWare$ installer/nemakisolr_installer_20131226.bin 
solr home root[default:/opt/nemakiware]: /home/nico/p/nemakisolr
cmis repository url[default:http://localhost:8080/NemakiWare/services/]: 
cmis repository name[default:bedroom]: 
cmis access user[default:admin]: 
cmis access password[default:admin]: 
install onto new tomcat(y/n)[default:n]: 
Target Tomcat directory[default:/opt/nemakiware/tomcat]: /home/nico/p/nemakiware/apache-tomcat-7.0.41
/usr/lib/ruby/1.9.1/fileutils.rb:1371:in `initialize': No such file or directory - /home/nico/p/nemakiware/apache-tomcat-7.0.41/webapps (Errno::ENOENT)
	from /usr/lib/ruby/1.9.1/fileutils.rb:1371:in `open'
	from /usr/lib/ruby/1.9.1/fileutils.rb:1371:in `block in copy_file'
	from /usr/lib/ruby/1.9.1/fileutils.rb:1370:in `open'
	from /usr/lib/ruby/1.9.1/fileutils.rb:1370:in `copy_file'
	from /usr/lib/ruby/1.9.1/fileutils.rb:477:in `copy_file'
	from /usr/lib/ruby/1.9.1/fileutils.rb:396:in `block in cp'
	from /usr/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
	from /usr/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
	from /usr/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
	from /usr/lib/ruby/1.9.1/fileutils.rb:395:in `cp'
	from ./setup_nemakisolr.rb:84:in `copy_war'
	from ./setup_nemakisolr.rb:137:in `main'
	from ./setup_nemakisolr.rb:142:in `<main>'
```

**Comment by linzhixing** [comment]
It was an older version's problem.
