### ISSUE TITLE
remoteFolder.createDocument fails

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/NemakiWare#292]
My code:
```
remoteFolder.createDocument(properties, contentStream(file), VersioningState.MAJOR);
```
NemakiWare error:
```
org.apache.chemistry.opencmis.commons.exceptions.CmisConstraintException: cmis:objectTypeId=my:type is not in the list of AllowedChildObjectTypeIds of the parent folder [cmis:objectId = ]createDocument: my-file.txt

	at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.convertStatusCode(AbstractAtomPubService.java:514)
	at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.post(AbstractAtomPubService.java:717)
	at org.apache.chemistry.opencmis.client.bindings.spi.atompub.ObjectServiceImpl.createDocument(ObjectServiceImpl.java:122)
	at org.apache.chemistry.opencmis.client.runtime.SessionImpl.createDocument(SessionImpl.java:1165)
	at org.apache.chemistry.opencmis.client.runtime.FolderImpl.createDocument(FolderImpl.java:77)
	at org.apache.chemistry.opencmis.client.runtime.FolderImpl.createDocument(FolderImpl.java:460)
```
Note how objectId (which is supposed to be created by NemakiWare within the same operation) is null.

Only happens if remoteFolder is not `/`, even though all folders are of type `cmis:folder`.

The remote folder seen in CMIS Workbench:
![screenshot from 2017-02-13 14-58-19](https://cloud.githubusercontent.com/assets/99590/22872485/e6535ac6-f1fc-11e6-84a4-a0ac8f16f489.png)
Root seen in CMIS Workbench:
![screenshot from 2017-02-13 15-01-42](https://cloud.githubusercontent.com/assets/99590/22872553/6e999e68-f1fd-11e6-9eb6-926a8e38a2a8.png)

**Comment by nicolas-raoul** [comment]
Solved by using recent integration branch.
